SELECT is_broker_enabled,is_honor_broker_priority_on FROM sys.databases WHERE name = 'CM_DAL'

--ALTER DATABASE CM_DAL SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE 
--ALTER DATABASE CM_DAL SET HONOR_BROKER_PRIORITY ON